### ISSUE TITLE
can not access

### ISSUE THREAD

**Issue by PremadeTV** [GRZ-D3V/grz-shop#1]
good day

I cannot access the NPCs!
I get this error message: https://prnt.sc/xv8mq3
when I start the resource I get this message: https://prnt.sc/xv8n84

**Comment by GRZ-D3V** [comment]
Hi,

from what I can see your error is:

**Search this in client:**
`ESX.UI.Menu.Open('default', GetCurrentResourceName(), 'actions', {title = 'youtoul', align = 'left', elements = elements }, function(data, menu)`

**Replace by:**
`ESX.UI.Menu.Open('default', GetCurrentResourceName(), 'actions', {title = _U('pharmacie'), align = 'left', elements = elements }, function(data, menu)`

If you have any others error like this just replace all `{title = _U('texthere')` by `{title = 'texthere'` in client side.

Thanks
